In [831]:
#1. Write a NumPy program to create an array with the values 1, 7, 13, 105    and determine the size of the memory occupied by the array.

In [832]:
import numpy as np
def function1():
    n1 = np.array([1,7,13,105])
    print(f"Size= {n1.size}")

In [833]:
function1()

Size= 4


In [834]:
#2. Write a NumPy program to create an element-wise comparison (greater,    greater_equal, less and less_equal) of two given arrays.

In [835]:
def function2():
    n1= np.array([10,30,50,80,70])
    n2= np.array([40,50,10,60,70])
   # print(f"arr1[0]>arr2[0] = {arr1[0]>arr2[0]}")
    print(np.greater(n1,n2))
    print(np.greater_equal(n1,n2))
    print(np.less(n1,n2))
    print(np.less_equal(n1,n2))
    

In [836]:
function2()

[False False  True  True False]
[False False  True  True  True]
[ True  True False False False]
[ True  True False False  True]


In [837]:
#3.  Write a NumPy program to create an array of 10 zeros, 10 ones, 10    fives, 10 tens, 10 twentys and 10 fiftys.

In [838]:
arr1= np.zeros(10)
arr2= np.ones(10)
arr3= (arr2*5)
arr4= (arr2*10)
arr5= (arr2*20)
arr6= (arr2*50)

In [839]:
print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)
print(arr6)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]
[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


In [840]:
#Write a NumPy program to create an array of integers from 30 to 70.

In [841]:
arr1= np.arange(30,70)
print(arr1)


[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [842]:
#5. Write a NumPy program to create an array of integers from 50 to 95.

In [843]:
arr1= np.arange(50,95)
print(arr1)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94]


In [844]:
#6. Write a NumPy program to create an array of all even integers from 20 to 80.

In [845]:
n4= np.arange(20,80,2)
print(n4)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78]


In [846]:
#7. Write a NumPy program to create an array of all odd integers from 20 to 80.

In [847]:
n5= np.arange(21,81,2)
print(n5)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


In [848]:
#. Write a NumPy program to generate an array of 15 random numbers from 10    to 40.
n4 = np.random.randint(10,40,15)
print(n4)

[15 10 36 14 20 19 34 27 16 10 29 25 39 33 27]


In [849]:
#9. Write a NumPy program to generate an array of 10 random numbers from 30    to 50.

In [850]:
n5= np.random.randint(30,50,10)
print(n5)

[35 38 37 35 48 32 38 42 36 42]


In [851]:
#10. Write a NumPy program to generate an array of 20 random numbers from 50    to 90.

In [852]:
n6= np.random.randint(50,90,20)
print(n6)

[86 55 67 76 65 66 67 76 82 73 88 76 70 89 52 68 72 87 66 75]


In [853]:
n1= np.array([11,22,33,44,55])
n2= np.array([10,20,30,40,50])
print(n1+n2)
print(n1-n2)
print(n1*n2)
print(n1/n2)

[ 21  42  63  84 105]
[1 2 3 4 5]
[ 110  440  990 1760 2750]
[1.1 1.1 1.1 1.1 1.1]


In [854]:
#12. Write a NumPy program to create a 3x4 matrix filled with values from 10     to 21.

In [855]:
n1 = np.arange(10,22)
print(n1)

[10 11 12 13 14 15 16 17 18 19 20 21]


In [856]:
n1 = n1.reshape([3,4])
print(n1)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [857]:
#13. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal     elements are 1, the rest are 0.

In [858]:
n1= np.diag([1, 1, 1])
print(n1)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [859]:
#14. Write a NumPy program to find the number of rows and columns in a given     matrix. 

In [860]:
import numpy as np
matrix = np.array([[14, 78, 10, 15], [7, 10, 8, 4]])
 
dimensions = matrix.shape
rows, columns = dimensions
 
print("Rows:", rows)
print("Columns:", columns)

Rows: 2
Columns: 4


In [861]:
15. Write a NumPy program to create a 5x5 zero matrix with elements on the     main diagonal equal to 1, 2, 3, 4, 5.

SyntaxError: invalid decimal literal (800289074.py, line 1)

In [ ]:
import numpy as np

n1= np.diag([1, 2, 3, 4, 5])
print(x)

In [ ]:
#18. Write a NumPy program to convert a list of numeric values into a one-    dimensional NumPy array.

In [ ]:
l1=([10,20,30,40])
n1=np.array(l1)
print(n1)

In [ ]:
#19. Write a NumPy program to create a 3x3 matrix with values ranging from 2     to 10.

In [ ]:
n1= np.arange(2,11)
print(n1)

In [ ]:
n1=n1.reshape(3,3)
print(n1)

In [ ]:
#20. Write a NumPy program to create an array with values ranging from 12 to 38.

In [ ]:
    n1=np.arange(12,38)
    print(n1)

In [ ]:
#21. Write a NumPy program to reverse an array (the first element becomes the last).

In [ ]:
n1=([10,20,30,40,50,60,70])
n1= np.flip(n1)

In [ ]:
print(n1)

In [ ]:
#22. Write a NumPy program to convert an data type into to a floating type.

In [ ]:
n4= np.array([1.1,2.3,4.4,5.5],dtype=np.float16)

In [ ]:
print(f"Dtype = {n4.dtype}")

In [ ]:
 #23 Write a NumPy program to convert a list array.

In [ ]:
l1 = [11,22,23,24,56,85]
print(l1)
print(f"Type = {type(l1)}")
arr = np.array(l1)
print(arr)
print(f"Type = {type(arr)}")

In [863]:
#24. Write a NumPy program to get the element-wise remainder of an array of division.

In [871]:
arr = np.array([10, 25, 44, 48, 50])
divisor = 5

remainder = np.remainder(arr, divisor)

print("arr : ",arr)
print("remainder: ", remainder)

arr :  [10 25 44 48 50]
remainder:  [0 0 4 3 0]


In [ ]:
25. Write a NumPy program to get the element-wise remainder of an array of numbers from 20 to 50 which are divisible by 3.

In [872]:
arr = np.arange(20, 51)

divisible_by_3 = arr[arr % 3 == 0]
remainder = divisible_by_3 % 20

print(arr)
print("Numbers divisible by 3:", divisible_by_3)
print("Element-wise remainder from 20:", remainder)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50]
Numbers divisible by 3: [21 24 27 30 33 36 39 42 45 48]
Element-wise remainder from 20: [ 1  4  7 10 13 16 19  2  5  8]
