In [73]:

def function1():
    l1 = [10,20,30,40,50]
    print(l1)
    print(f"Type = {type(l1)}")
    print(f"l1[0] Type = {type(l1[0])}")


In [74]:
function1()

[10, 20, 30, 40, 50]
Type = <class 'list'>
l1[0] Type = <class 'int'>


In [75]:
import numpy as np

In [76]:
def function3():
    arr = np.array([10,20,30,40,50,60])
    print(arr)
    print(f"Type= {type(arr)}")
    print(f"Dtype= {arr.dtype}")
    print(f"Itemsize={arr.itemsize}")
    print(f"NDIM={arr.ndim}")
    print(f"NBYTES={arr.nbytes}")


In [77]:
function3()

[10 20 30 40 50 60]
Type= <class 'numpy.ndarray'>
Dtype= int64
Itemsize=8
NDIM=1
NBYTES=48


In [78]:
def function2():
    n_arr= np.array([10,20,30,40,50])
    print(f"type= {type(n_arr)}")

In [79]:
function2()

type= <class 'numpy.ndarray'>


In [80]:
def printProperties(arr):
    print(arr)
    print(f"Type = {type(arr)}")
    print(f"Dtype = {arr.dtype}")
    print(f"Item Size = {arr.itemsize}")
    print(f"Size = {arr.size}")
    print(f"NDIM = {arr.ndim}")
    print(f"NBYTES = {arr.nbytes}")

In [81]:
n1= np.array([10,20,30,40,50,60])
printProperties(n1)

[10 20 30 40 50 60]
Type = <class 'numpy.ndarray'>
Dtype = int64
Item Size = 8
Size = 6
NDIM = 1
NBYTES = 48


In [86]:
n2 = np.array([50,60,70],dtype=np.int8)
printProperties(n2)

[50 60 70]
Type = <class 'numpy.ndarray'>
Dtype = int8
Item Size = 1
Size = 3
NDIM = 1
NBYTES = 3


In [87]:
n3= np.array([80,90,100,110],dtype= np.int64)
printProperties(n3)

[ 80  90 100 110]
Type = <class 'numpy.ndarray'>
Dtype = int64
Item Size = 8
Size = 4
NDIM = 1
NBYTES = 32


In [88]:
n4= np.array([1.1,2.3,4.4,5.5],dtype=np.float16)
printProperties(n4)


[1.1 2.3 4.4 5.5]
Type = <class 'numpy.ndarray'>
Dtype = float16
Item Size = 2
Size = 4
NDIM = 1
NBYTES = 8


In [89]:
n5 = np.array(["C","C++","Python","Java"])
printProperties(n5)

['C' 'C++' 'Python' 'Java']
Type = <class 'numpy.ndarray'>
Dtype = <U6
Item Size = 24
Size = 4
NDIM = 1
NBYTES = 96
